
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 20 22:00:34 EST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int PLUSPLUS = 7;
  public static final int NUMBER = 3;
  public static final int SEMI = 8;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int error = 1;
  public static final int PRINT = 2;
  public static final int TIMES = 6;
  public static final int COMMENT = 9;
}

